### ISSUE TITLE
Rename to standardese.github.io

### ISSUE THREAD

**Issue by saraedum** [standardese/standardese.github.io#1]
Should we rename this as pointed out by @foonathan https://github.com/standardese/standardese/issues/125#issuecomment-537894012

**Comment by bresilla** [comment]
I think for that to work, the main repository has to be changed, otherwise i don't think we can have two repositories with the same name

**Comment by bresilla** [comment]
I mean, changed to src or main ...

**Comment by saraedum** [comment]
I just renamed it. Seemed to work.

**Comment by saraedum** [comment]
It's now here: https://standardese.github.io/

**Comment by saraedum** [comment]
Feel free to undo if I got this wrong somehow.

**Comment by bresilla** [comment]
Perfect!
I didn't know you could do that.

Thanks :)
