### ISSUE TITLE
develop & master

### ISSUE THREAD

**Issue by saraedum** [standardese/standardese.github.io#3]
@bresilla I've seen you set up two branches here as in the main repo. I am not actually sure that I want to keep that separation. Imho it tends to create a bit of overhead that we might not want to handle with the limited resources we have. (It was probably introduced for some major rewrite where I would have done the same of course.)

I usually prefer to just have a master that contains the current development version and tag stable versions. And release often instead of keeping a more stable fork around.

In particular for documentation it's probably unrealistic that we'll be able to maintain two separate threads of documentation. So we should probably just tag documentation whenever we tag a release. What do you think?

**Comment by bresilla** [comment]
Sure thing.
Actually that was not supposed to happen. That's because locally i use git flow and i pushed all, so the develop branch got pushed too!

I'll delete develop now. :)
